class Config(object):
    DEBUG = True
    FPS = 60
    GAME_CAPTION = "Bomberman"
    SCREEN_HEIGHT = 750
    SCREEN_WIDTH = 750
    ENABLE_BOX_GENERATION = True
    COLLISION_TOLLERANCE = 25
    BOX_MAGIC_RANDOM_NUMBER = 6
    DEBUG_SHOW_BOMB_TIMERS = False
